### ISSUE TITLE
`A javascript error occured in the main process` when clicking on internal link

### ISSUE THREAD

**Issue by jjst** [zulip/zulip-electron#17]
I got the following error when clicking on an internal link to another stream, with an error window popping up telling me "A JavaScript error occurred in the main process":

```
Uncaught Exception:
TypeError: url.match is not a function
    at module.exports (/home/jjst/dev/zulip-electron/node_modules/wurl/wurl.js:69:13)
    at linkIsInternal (/home/jjst/dev/zulip-electron/app/main/link_helper.js:5:25)
    at EventEmitter.page.on (/home/jjst/dev/zulip-electron/app/main/index.js:91:13)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.<anonymous> (/home/jjst/dev/zulip-electron/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/guest-window-manager.js:106:16)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at EventEmitter.webContents.on (/home/jjst/dev/zulip-electron/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/browser-window.js:26:13)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

**Comment by jjst** [comment]
Not restricted to internal links, I just had the same issue on a vanilla URL.

**Comment by akashnimare** [comment]
@jjst could you test it now?

**Comment by jjst** [comment]
I haven't seen the issue when testing with the latest build.
